### ISSUE TITLE
Shortcut key no longer works on MacOS Ventura/Safari 16.1

### ISSUE THREAD

**Issue by davidwgoodman** [shamoon/fbt#13]
Hi there - I've noticed that the extension no longer works with MacOS Ventura/Safari 16.1.

Hitting the key I use (F) does not load the selected Feedly item in a new tab.

I've tried:

- changing to a different key
- uninstalling and reinstalling the extension
- logging out of Feedly and back in
- Quitting and restarting the browser

No effect in all cases.

**Comment by shamoon** [comment]
Thanks for the heads up. Yea feedly have changed their structure again. 

I submitted a new version to the app store that should fix this, should be available soon.

**Comment by davidwgoodman** [comment]
Thanks, tested and confirmed working again on the above browser/OS combo. Appreciate the fast update!
