### ISSUE TITLE
Latest update not functioning

### ISSUE THREAD

**Issue by davidwgoodman** [shamoon/fbt#15]
The latest version worked very briefly (the first time I used the shortcut key) then stopped working. Not sure if it was just bad timing with a Feedly release or if there's another issue. I have uninstalled and reinstalled and changed the shortcut key I use with no effect.

**Comment by shamoon** [comment]
Thanks. I've rewritten things to hopefully be more stable through changes, a little frustrating all the whack-a-mole. I submitted v1.1.3 to the app store.

**Comment by davidwgoodman** [comment]
Appreciated.

**Comment by mathomp4** [comment]
Not to revive a zombie issue, but I can only see v1.1.2 on the App Store. Is there something special needed to get v1.1.3?

**Comment by shamoon** [comment]
Zombie indeed. I literally forgot to hit submit 😑

Just did.
