### ISSUE TITLE
Extension not working as expected

### ISSUE THREAD

**Issue by mathomp4** [shamoon/fbt#16]
I grabbed v1.1.3 (thanks @shamoon) and enabled in Safari. However, I can't seem to get anything in a background tab from Feedly.

I tried mapping to `i` (my preferred shortcut) and nothing. If I switch to the default of `v` it loads in foreground. 

Is there maybe something else I need to turn on/off in the Safari settings?

**Comment by shamoon** [comment]
I can't reproduce the issue, see attached. Just to make sure, did you allow the extension on 'feedly.com'? I think that previously wasn't necessary but now may be in newer versions of Safari.


https://github.com/user-attachments/assets/af77de22-fd68-44cc-85a0-dca7c854d162



<img width="551" alt="Screenshot 2024-10-18 at 12 17 28 PM" src="https://github.com/user-attachments/assets/af54d705-1cb6-441a-9cb8-7b7b299ef606">

**Comment by mathomp4** [comment]
Hmm. Yeah, I have it allowed:

<img width="948" alt="Screenshot 2024-10-18 at 3 44 23 PM" src="https://github.com/user-attachments/assets/2440c652-6e0b-4126-b4bd-ec70cf918fea">

And it's the latest version:

<img width="948" alt="Screenshot 2024-10-18 at 3 47 26 PM" src="https://github.com/user-attachments/assets/d37b358f-33e3-4dd8-9a66-9fe7e484e20f">

and I turned off every other extension just in case. And yet:

https://github.com/user-attachments/assets/501aba2b-c32d-4f78-8160-2b7728f1c7e7

The time you see the tab pop up is when I press `v`. I was pressing `i` a lot before that and nothing. 

I am baffled. I must have done...something in a setting wrong.
